{{- if and .Values.podDisruptionBudget.enabled (not .Values.autoscaling.enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "releasepilot.fullname" . }}
  labels:
    {{- include "releasepilot.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "releasepilot.selectorLabels" . | nindent 6 }}
{{- end }}
