#!/usr/bin/env python3
"""Render a production release runbook from a redacted workflow manifest.

This script intentionally uses only the Python standard library so it can run
inside the deployment repository's GitHub Actions workflow. It writes one
stable file per production release; a later workflow run replaces that file.
"""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path


def safe_release_name(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "-", value).strip(".-")
    if not cleaned:
        raise ValueError("Release number contains no usable filename characters")
    return cleaned


def bullet_lines(items: list[str]) -> list[str]:
    return [f"- {item}" for item in items] or ["- No items recorded."]


def render(manifest: dict, title: str, additional_information: str) -> str:
    release_number = manifest["release_number"]
    helm_changes = manifest.get("helm_changes", [])
    jira_issues = manifest.get("jira_issues", [])
    change_flags: list[str] = []
    component_rows: list[tuple[str, str, str]] = []
    risk_points = 0

    for change in helm_changes:
        component = change.get("component", "Unknown component")
        current_image = change.get("current_image") or "not recorded"
        target_image = change.get("target_image") or "not recorded"
        component_rows.append((component, target_image, current_image))
        if current_image != target_image:
            change_flags.append(f"{component}: image {current_image} → {target_image}")
        if change.get("replica_change"):
            change_flags.append(f"{component}: replicas {change['replica_change']}")
            risk_points += 1
        if change.get("resource_change"):
            change_flags.append(f"{component}: CPU or memory settings changed")
            risk_points += 1
        if change.get("config_change"):
            change_flags.append(f"{component}: configuration reference changed")
            risk_points += 1
        if change.get("secret_reference_changed"):
            change_flags.append(f"{component}: secret reference changed (value excluded)")
            risk_points += 1

    migration_keys = [item.get("key", "Unknown Jira issue") for item in jira_issues if item.get("requires_data_migration") or item.get("issue_type") == "migration"]
    downtime_keys = [item.get("key", "Unknown Jira issue") for item in jira_issues if item.get("requires_downtime")]
    risk_points += (2 * len(migration_keys)) + (2 * len(downtime_keys))
    risk = "high" if risk_points >= 4 else "medium" if risk_points else "standard"
    heading = title.strip() or f"{release_number} production release"
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    previous_stable_rows = [f"| {component} | {current} |" for component, _target, current in component_rows] or ["| Release scope not yet discovered | Confirm in ArgoCD History |"]

    lines = [
        f"# {release_number}-RUNBOOK — {heading}",
        "",
        "> This document is generated by the approved production-release workflow. Re-running the workflow for the same release updates this file.",
        "",
        "## 1. Release information",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| Release version | {release_number} |",
        "| Environment | Production |",
        "| Change ticket | Retrieved from Jira when that integration is enabled |",
        f"| Release date | {generated_at} |",
        "| Release engineer | Confirm in the approved change record |",
        "| Application IT owner | Confirm in the approved change record |",
        "| Deployment method | GitOps (GitHub + ArgoCD) |",
        "| Rollback method | ArgoCD revision rollback |",
        f"| Risk | {risk.title()} |",
        f"| Source branch/ref | {manifest.get('repository', 'Not supplied')} @ {manifest.get('git_ref', 'Not supplied')} |",
        "",
        "## 2. Release scope",
        "",
        "### 2.1 Components included",
        "",
        "| Component | Target image/version | Previous stable version |",
        "| --- | --- | --- |",
        *[f"| {component} | {target} | {current} |" for component, target, current in component_rows],
        "",
        "### 2.2 Release contents",
        *bullet_lines([f"{item.get('key', 'Unknown')}: {item.get('summary', 'No summary')}" for item in jira_issues]),
        "",
        "### 2.3 Deployment evidence",
        *bullet_lines(change_flags),
    ]
    if not component_rows:
        lines.insert(lines.index("", lines.index("| --- | --- | --- |") + 1), "| No changed component found | — | — |")
    if additional_information.strip():
        lines.extend(["", "### Additional information", additional_information.strip()])
    lines.extend([
        "",
        "## 3. Release readiness checks",
        "- [ ] Confirm production approval, release window, component owners, and the final release scope.",
        "- [ ] Capture baseline health, alerts, errors, restart counts, and running image versions.",
        "- [ ] Confirm dependency availability before starting the rollout.",
        *([f"- [ ] Confirm a tested backup and approved migration plan for: {', '.join(migration_keys)}."] if migration_keys else []),
        *([f"- [ ] Confirm maintenance-window approval and customer communication for: {', '.join(downtime_keys)}."] if downtime_keys else []),
        "",
        "## 4. Deployment procedure",
        "",
        "### 4.1 Change ticket update",
        "- [ ] Update the approved change record with the release version, scope, approvals, and final evidence links.",
        "",
        "### 4.2 Promote UAT to PROD",
        "- [ ] Create and approve the UAT-to-PROD pull request through the approved GitOps process.",
        "- [ ] Deploy only through the approved production workflow.",
        "",
        "### 4.3 ArgoCD synchronization",
        "- [ ] Sync only applications listed in the release scope.",
        "- [ ] Confirm every application becomes **Healthy** and **Synced**.",
        "",
        "### 4.4 Deployment verification",
        "- [ ] Confirm available replicas, readiness, key user journeys, and dependency connectivity.",
        "- [ ] Confirm pods are running with no CrashLoopBackOff or failed containers.",
        "- [ ] Confirm the deployed image matches the target version recorded above.",
        "- [ ] Compare errors, latency, and restarts with the captured pre-release baseline.",
        "- [ ] Record the production outcome and any follow-up work in the change record.",
        "",
        "## 5. Rollback plan",
        "",
        "### 5.1 Rollback criteria",
        "- Critical functionality is unavailable, the application is unhealthy, errors grow materially, or the business owner requests rollback.",
        "",
        "### 5.2 Rollback procedure",
        "- [ ] In ArgoCD, select the previous stable revision from **History and Rollback**.",
        "- [ ] Redeploy and synchronize the selected revision.",
        "- [ ] Confirm every affected application is **Healthy** and **Synced**.",
        "",
        "### 5.3 Previous successful deployed versions",
        "",
        "| Component | Previous stable version |",
        "| --- | --- |",
        *previous_stable_rows,
        "",
        "_This runbook is advisory. It does not perform deployment or rollback actions._",
    ])
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a stable production release runbook")
    parser.add_argument("--manifest", required=True, type=Path)
    parser.add_argument("--output-directory", required=True, type=Path)
    parser.add_argument("--title", default="")
    parser.add_argument("--additional-information", default="")
    args = parser.parse_args()
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    release_number = safe_release_name(str(manifest.get("release_number", "")))
    manifest["release_number"] = release_number
    args.output_directory.mkdir(parents=True, exist_ok=True)
    output = args.output_directory / f"{release_number}-RUNBOOK.md"
    output.write_text(render(manifest, args.title, args.additional_information), encoding="utf-8")
    print(output)


if __name__ == "__main__":
    main()
